### ISSUE TITLE
readproto is working on Julia 0.3 but does not work on Julia 0.4

### ISSUE THREAD

**Issue by nilbdk** [tanmaykm/ProtoBuf.jl#52] opened 2015-11-19 15:23 UTC
I've just started to Julia so this may not be a problem, i have no idea. 
It works on Julia 0.3
```
julia> conn = RedisConnection(;host="<HOST>", port=<PORT>, db=<DB>)
Redis.RedisConnection("HOST,"",DB,TCPSocket(open, 0 bytes waiting))

julia> symbolbuf= get(conn, "<KEY>")
"\bÈ\u90\x01\x12\rF_ONRPQ0916S0\x1a\x1cONRPQ Eylul 2016 Vadeli (S0)X\x02a\0\0\0\0\0\0\0\0j\n30.09.2016r\x05ONRPQ\u81\x01\0\0\0\0\0\0\0\0\u89\x01\0\0\0\0\0\0\0\0±\x02{\x14®Gáz\u84?"

julia> io = PipeBuffer(symbolbuf.data)
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=false, append=true, size=117, maxsize=Inf, ptr=1, mark=-1)

julia> result = readproto(io, DerivativeMessage());
ERROR: EOFError: read end of file
 in read_sub at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in skip_field at /Users/niluferbidik/.julia/v0.4/ProtoBuf/src/codec.jl:295
 in readproto at /Users/niluferbidik/.julia/v0.4/ProtoBuf/src/codec.jl:318
 in readproto at /Users/niluferbidik/.julia/v0.4/ProtoBuf/src/codec.jl:308
```

**Comment by tanmaykm** [comment] 2015-11-19 17:40
Is there some way to reproduce this locally?

You could also get some more details by flipping the comments here to switch on logging: https://github.com/tanmaykm/ProtoBuf.jl/blob/51fbf7607b6ecb732e48d0b2317a5927335323c5/src/ProtoBuf.jl#L32

**Comment by nilbdk** [comment] 2015-11-20 08:29
You can use proto file below

```
"\bÈ\u90\x01\x12\rF_ONRPQ0916S0\x1a\x1cONRPQ Eylul 2016 Vadeli (S0)X\x02a\0\0\0\0\0\0\0\0j\n30.09.2016r\x05ONRPQ\u81\x01\0\0\0\0\0\0\0\0\u89\x01\0\0\0\0\0\0\0\0±\x02{\x14®Gáz\u84?"
```
[Derivative.txt](https://github.com/tanmaykm/ProtoBuf.jl/files/39857/Derivative.txt)

**Comment by tanmaykm** [comment] 2015-11-20 09:02
Could you also post a binary file for the serialized data?

I suspect the data will get corrupted when moved back and forth as a
string. And if that's what you are receiving from redis, it could be
causing this error. Julia strings underwent significant changes between
Julia 0.3 and 0.4 and that could explain the breakage.

**Comment by tanmaykm** [comment] 2015-11-20 09:06
And, if you must store it as a string, you could encode and decode it
appropriately (e.g. base64)

**Comment by tanmaykm** [comment] 2015-11-21 02:07
Tried both `readproto` and `writeproto` with the spec file and found them working. I suspect this error is because of data corruption as suggested above. Closing this as not a `ProtoBuf.jl` issue.

Please reopen if you still see it.

**Closed by tanmaykm** 2015-11-21 02:07 UTC
